version: 2
updates:
  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Check for updates to Python dependencies (main app)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Check for updates to Python dependencies (app-fast)
  - package-ecosystem: "pip"
    directory: "/app-fast"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependencies"
    commit-message:
      prefix: "deps(app-fast)"
      include: "scope"

  # Check for updates to Docker base image
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Check for updates to npm dependencies (app-static)
  - package-ecosystem: "npm"
    directory: "/app-static"
    schedule:
      interval: "weekly"
    labels:
      - "javascript"
      - "dependencies"
    commit-message:
      prefix: "deps(app-static)"
      include: "scope"
